### ISSUE TITLE
NWEv6_new.py indicator merge error while running

### ISSUE THREAD

**Issue by jashan1498** [anakein/beastbotXB#4]
got this error while running/backtesting the v6_new strat 

running it on : 
timeframe  : 5m

```
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1161, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1059, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/freqtrade/freqtrade/strategy/interface.py", line 1081, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 1081, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 1096, in advise_indicators
    dataframe = _create_and_merge_informative_pair(
  File "/freqtrade/freqtrade/strategy/informative_decorator.py", line 134, in _create_and_merge_informative_pair
    dataframe = merge_informative_pair(dataframe, inf_dataframe, strategy.timeframe, timeframe,
  File "/freqtrade/freqtrade/strategy/strategy_helper.py", line 48, in merge_informative_pair
    raise ValueError("Tried to merge a faster timeframe to a slower timeframe."
ValueError: Tried to merge a faster timeframe to a slower timeframe.This would create new rows, and can throw off your regular indicators.
```

**Comment by Deleriumdelicious** [comment]
I'm running the previous and new version in dry-run but I don't have any trade the last couple of days. Bot is running though and there are more than enough pairs in the whitelist. Is it correct no trades have happened the last couple of days?

**Comment by Deleriumdelicious** [comment]
Can you also please specify which additional dependencies we have to install next to the ones that are already included in Freqtrade?

**Comment by Deleriumdelicious** [comment]
@jashan1498 , did you already solve the error in the meantime perhaps? @anakein can you please help us with this issue? Are there certain settings or configs we have to adjust?

**Comment by simwai** [comment]
You just need to use 1m timeframe

**Comment by Jeerjmin** [comment]
Why backtest show negative profit ? But dry-run works well with positive?
@anakein
